# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93ce97a6ae24731fbd17371a0ffd503036482b22124b2d1c754e6bb8acd934799e5c43493f96cf557a29d8aacdd908853453d8a353d77a21136401c79fbf9c88

test:
  secret_key_base: e3f44d0ae0ce8de8e3aa41048f508b33d7f73e9a57d44f9dc04085b166f4144b2c560b77d896341dea15fee30f61769d146cacede3eec93efd52456de8dc90f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
